---
apiVersion: v1
kind: Pod
metadata:
  annotation:
    io.podman.annotations.infra.name: pg-infra-pod
  labels:
    app: app-db
  name: app-db
spec:
  containers:
  - name: pg-pod
    image: docker.io/library/postgres:15
    args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: appuser
    - name: POSTGRES_PASSWORD
      value: apppass
    - name: POSTGRES_DB
      value: appdb
    ports:
    - containerPort: 5432
      hostPort: 5432
    livenessProbe:
      initialDelaySeconds: 30
      tcpSocket:
        port: 5432
      timeoutSeconds: 1
    stdin: true
    tty: true
    readinessProbe:
      exec:
        command:
        - pg_isready
      initialDelaySeconds: 5
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: storage
  volumes:
  - name: storage
    emptyDir: {}